### ISSUE TITLE
The German demo text has spelling errors

### ISSUE THREAD

**Issue by pythoneer** [greyblake/whatlang-website#1]
I don't know if you aware of it but the German demo text has a few spelling errors. I am unsure if this is intentional to show that the engine is working even if you have spelling errors. If you're interested in correcting them i can offer you my help. 

The first sentence has only minor mistakes:

> Wenn du vershtest, was ich schreibe, dann du wahrscheinlich deutsch bist.
> Wenn Du verstehst, was ich schreibe, dann bist Du wahrscheinlich deutsch.

The second sentence is a little bit harder because i don't really know what the intention was in the first place for the second half of the sentence

> Für dich habe ich aber kleinen Reminder: kein Bier für vier. Ansonst geht es..... immer los!!!

If you present me an English version or a hint to a proverb you wanted to use i can probably try to translate it :)

btw: Love the Project!  

EDIT:
The last sentence is probably "no beer before four (o'clock)"? 

> Für Dich habe ich eine kleine Gedankenstütze: Kein Bier vor Vier. Ansonsten geht es..... immer los!!!

**Comment by greyblake** [comment]
Was fixed, thanks for the PR
